FROM golang:1.12-alpine

ENV GOPATH /go
ENV CGO_ENABLED 0
ENV GO111MODULE on
ENV GOPROXY=https://goproxy.io

WORKDIR /root/minio-storage

COPY ./ ./
RUN \
    go mod download && \
    go build -o /usr/bin/minio-storage main.go

FROM alpine:3.9
COPY --from=0 /usr/bin/minio-storage /usr/bin/minio-storage

RUN chmod +x /usr/bin/minio-storage

ENV PORT=8080
EXPOSE 8080

ENTRYPOINT ["/usr/bin/minio-storage"]
